const actions = {
  SEARCH_BOX_CONTROL: 'SEARCH_BOX_CONTROL',
  SORT_BOX_CONTROL: 'SORT_BOX_CONTROL',
  SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
  CLEAN_UP_MODALS: 'CLEAN_UP_MODALS',
  PROMPT_BOX_CONTROL: 'PROMPT_BOX_CONTROL',
  LOADING: 'LOADING',
  SET_BUGS_DATA: 'SET_BUGS_DATA',
  SELECTED_BUG_ID: 'SELECTED_BUG_ID',
  QUERY_BUGS: 'QUERY_BUGS',
  INFO_BOX_DATA: 'INFO_BOX_DATA',
  EDIT_ACCOUNT_MODAL: 'EDIT_ACCOUNT_MODAL',
  THEME_SWITCHER_MODAL: 'THEME_SWITCHER_MODAL',
  AUTH: 'AUTH',
};

export default actions;
