export const ActionTypes = {
	SEARCH_BOX_CONTROL: 'SEARCH_BOX_CONTROL',
	SORT_BOX_CONTROL: 'SORT_BOX_CONTROL',
	PROMPT_BOX_CONTROL: 'PROMPT_BOX_CONTROL',
	LOADING: 'LOADING',
	SET_BUGS_DATA: 'SET_BUGS_DATA',
	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	SELECTED_BUG_ID: 'SELECTED_BUG_ID',
	CLEAN_UP_MODALS: 'CLEAN_UP_MODALS',
};
